import { useMemo, useState } from "react";
import { Activity, Bell, ChevronRight, CircleHelp, Crosshair, Database, Filter, Flame, Layers3, MapPin, Radio, RefreshCw, Search, ShieldAlert, Sparkles, Telescope, TimerReset, Waves, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";

const classificationOptions = ["All classes", "Industrial", "Wildfire", "Ag burn", "Gas flare", "Mining", "Unknown"];
const riskOptions = ["All risk", "Critical", "Elevated", "Watch", "Unassessed"];

export default function Home() {
  const [classFilter, setClassFilter] = useState("All classes");
  const [riskFilter, setRiskFilter] = useState("All risk");
  const [query, setQuery] = useState("");
  const [isRefreshing, setIsRefreshing] = useState(false);
  const filteredLabel = useMemo(() => [classFilter !== "All classes" ? classFilter : null, riskFilter !== "All risk" ? riskFilter : null].filter(Boolean).join(" · ") || "All signals", [classFilter, riskFilter]);
  const refresh = () => { setIsRefreshing(true); window.setTimeout(() => setIsRefreshing(false), 900); };

  return <main className="min-h-screen overflow-hidden bg-[#050816] text-slate-100"><div className="starfield" aria-hidden="true" /><div className="nebula nebula-cyan" aria-hidden="true" /><div className="nebula nebula-violet" aria-hidden="true" /><div className="planet-orb cyan" style={{ left: "18%", top: "24%" }} aria-hidden="true" /><div className="planet-orb violet" style={{ left: "64%", top: "66%" }} aria-hidden="true" /><div className="planet-orb blue" style={{ left: "84%", top: "18%" }} aria-hidden="true" />
    <div className="relative z-10 mx-auto max-w-[1600px] px-4 py-5 sm:px-7 lg:px-10">
      <header className="mb-7 flex flex-col gap-5 border-b border-white/10 pb-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-4"><div className="brand-mark"><Telescope size={22} strokeWidth={1.5} /></div><div><div className="flex items-center gap-3"><p className="eyebrow">ORBITAL INTELLIGENCE</p><span className="live-dot" /><span className="text-[10px] uppercase tracking-[0.22em] text-cyan-200/70">Live system</span></div><h1 className="mt-1 text-2xl font-semibold tracking-[-0.03em] text-white sm:text-3xl">Thermal Hotspot Intelligence</h1></div></div><div className="flex flex-wrap items-center gap-3"><div className="status-chip"><Database size={14} /><span>FIRMS stream</span><span className="status-pill">Awaiting sync</span></div><Button onClick={refresh} variant="outline" className="border-white/15 bg-white/[0.04] text-slate-200 hover:bg-white/10 hover:text-white"><RefreshCw size={15} className={isRefreshing ? "mr-2 animate-spin" : "mr-2"} />Refresh</Button><Button variant="outline" className="border-white/15 bg-white/[0.04] text-slate-200 hover:bg-white/10 hover:text-white"><Bell size={15} className="mr-2" />Alerts</Button></div></header>
      <section className="mb-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={<Activity size={16} />} label="Total detections" value="—" helper="Live ingest pending" tone="cyan" /><MetricCard icon={<ShieldAlert size={16} />} label="Industrial candidates" value="—" helper="Risk threshold: 0.72" tone="rose" /><MetricCard icon={<Sparkles size={16} />} label="AI assessments" value="—" helper="Evidence model ready" tone="violet" /><MetricCard icon={<TimerReset size={16} />} label="Recent activity" value="—" helper="Last 24 hours" tone="amber" /></section>
      <section className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(360px,0.72fr)]"><div className="glass-panel overflow-hidden rounded-2xl"><div className="flex flex-col gap-4 border-b border-white/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Crosshair size={16} className="text-cyan-300" /><h2 className="section-title">Investigation field</h2></div><p className="mt-1 text-sm text-slate-400">Explore geospatial evidence across the current FIRMS window.</p></div><div className="flex items-center gap-2"><span className="data-note"><Waves size={13} /> No live detections loaded</span><Button size="icon" variant="ghost" className="text-slate-400 hover:bg-white/10 hover:text-white"><Layers3 size={17} /></Button></div></div><div className="relative min-h-[440px] overflow-hidden bg-[#071329] sm:min-h-[520px]"><div className="map-grid" /><div className="map-contours" /><div className="map-label map-label-a">N 23.5° · E 87.2°</div><div className="map-label map-label-b">INDUSTRIAL BELT / SECTOR 04</div><div className="map-label map-label-c">THERMAL SURVEY GRID</div><div className="map-ring ring-one" /><div className="map-ring ring-two" /><div className="map-empty-state"><div className="empty-signal"><Radio size={22} /></div><p className="mt-4 font-medium text-white">Waiting for orbital signals</p><p className="mt-1 max-w-[240px] text-center text-xs leading-5 text-slate-400">Connect the NASA FIRMS stream to populate this investigation field.</p><Button onClick={refresh} variant="outline" className="mt-5 border-cyan-300/25 bg-cyan-300/5 text-cyan-100 hover:bg-cyan-300/15">Check stream <ChevronRight size={14} className="ml-1" /></Button></div><div className="absolute bottom-4 left-4 flex items-center gap-4 rounded-xl border border-white/10 bg-[#061024]/75 px-3 py-2 text-[10px] uppercase tracking-[0.16em] text-slate-400 backdrop-blur-md"><span className="flex items-center gap-2"><span className="legend-dot cyan" />Live</span><span className="flex items-center gap-2"><span className="legend-dot rose" />High risk</span><span className="flex items-center gap-2"><span className="legend-dot violet" />Historical</span></div></div></div>
      <aside className="glass-panel flex min-h-[560px] flex-col rounded-2xl"><div className="border-b border-white/10 p-5"><div className="flex items-start justify-between"><div><p className="eyebrow">SIGNAL QUEUE</p><h2 className="section-title mt-2">Hotspot detections</h2></div><Badge variant="outline" className="border-white/15 bg-white/[0.04] text-slate-300">{filteredLabel}</Badge></div><div className="relative mt-5"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search coordinates or source" className="border-white/10 bg-black/20 pl-9 text-sm text-white placeholder:text-slate-600 focus-visible:ring-cyan-300/40" /></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1"><Filter size={14} className="mt-2 shrink-0 text-slate-500" /><FilterSelect value={classFilter} onChange={setClassFilter} options={classificationOptions} /><FilterSelect value={riskFilter} onChange={setRiskFilter} options={riskOptions} /></div></div><div className="flex flex-1 flex-col items-center justify-center p-7 text-center"><div className="empty-signal small"><Flame size={18} /></div><p className="mt-4 text-sm font-medium text-slate-200">No detections to inspect</p><p className="mt-2 max-w-[250px] text-xs leading-5 text-slate-500">The list will show satellite detections once the FIRMS importer completes its first sync.</p><div className="mt-6 flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-cyan-300/60"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300" />Stream status: idle</div></div><div className="border-t border-white/10 p-4"><div className="flex items-center justify-between text-xs text-slate-500"><span>Historical window</span><span>30 days</span></div><Progress value={0} className="mt-3 h-1 bg-white/10" /></div></aside></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-[0.85fr_1.15fr]"><div className="glass-panel rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">CLASSIFICATION MIX</p><h2 className="section-title mt-2">Source signatures</h2></div><Sparkles size={18} className="text-violet-300" /></div><div className="mt-6 space-y-4"><Breakdown label="Industrial thermal source" value="—" tone="bg-cyan-300" /><Breakdown label="Wildfire / agricultural" value="—" tone="bg-amber-300" /><Breakdown label="Gas flare / mining" value="—" tone="bg-violet-300" /><Breakdown label="Unknown / review" value="—" tone="bg-slate-500" /></div></div><div className="glass-panel rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">ASSESSMENT WORKBENCH</p><h2 className="section-title mt-2">Evidence summary</h2></div><CircleHelp size={18} className="text-slate-500" /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><EvidenceTile icon={<MapPin size={16} />} label="Location context" value="Pending" /><EvidenceTile icon={<Activity size={16} />} label="Detection history" value="Pending" /><EvidenceTile icon={<ShieldAlert size={16} />} label="Risk assessment" value="Pending" /></div><div className="mt-5 rounded-xl border border-dashed border-white/12 bg-black/10 p-4 text-sm leading-6 text-slate-400">Select a hotspot to view the AI explanation, nearby industrial context, land-use indicators, and the evidence chain used to reach its assessment.</div></div></section>
      <footer className="flex flex-col gap-2 border-t border-white/10 py-6 text-[10px] uppercase tracking-[0.18em] text-slate-600 sm:flex-row sm:items-center sm:justify-between"><span>NASA FIRMS · ORBITAL SIGNAL PROCESSING</span><span>Assessment layer is decision support, not a confirmed incident report.</span></footer>
    </div>
  </main>;
}

function MetricCard({ icon, label, value, helper, tone }: { icon: React.ReactNode; label: string; value: string; helper: string; tone: string }) { return <div className="glass-panel rounded-2xl p-4"><div className="flex items-center justify-between"><span className={`metric-icon ${tone}`}>{icon}</span><span className="text-[10px] uppercase tracking-[0.17em] text-slate-600">Telemetry</span></div><p className="mt-4 text-xs uppercase tracking-[0.13em] text-slate-500">{label}</p><p className="mt-1 text-3xl font-semibold tracking-[-0.04em] text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{helper}</p></div>; }
function FilterSelect({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: string[] }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="h-8 rounded-lg border border-white/10 bg-[#0a1428] px-2 text-[11px] text-slate-300 outline-none focus:border-cyan-300/40">{options.map((option) => <option key={option}>{option}</option>)}</select>; }
function Breakdown({ label, value, tone }: { label: string; value: string; tone: string }) { return <div><div className="mb-2 flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-400"><span className={`h-2 w-2 rounded-full ${tone}`} />{label}</span><span className="font-mono text-slate-500">{value}</span></div><div className="h-1 overflow-hidden rounded-full bg-white/8"><div className={`h-full w-0 rounded-full ${tone}`} /></div></div>; }
function EvidenceTile({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-white/[0.025] p-4"><div className="text-cyan-300/80">{icon}</div><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-200">{value}</p></div>; }
